# Generated by Django 4.2.7 on 2023-11-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img_url',
            field=models.URLField(default='your_default_image_url'),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='Default Name', max_length=200),
        ),
    ]
